### ISSUE TITLE
Force new rotate when commercetools scope changes

### ISSUE THREAD

**Issue by tleguijt** [labd/mach-component-aws-commercetools-token-refresher#2]
In the `secrets` module, the `aws_secretsmanager_secret_rotation` resource should force a new rotate when the `var.scopes` changes.

If we could re-create this resource when the scope changes, AWS will trigger a new rotate. 
At the moment there doesn't seem to be an easy way to trigger this.

**Comment by korsvanloon** [comment]
If I read it correctly, we should be able to rotate the token using the API of the AWS secrets manager by calling `RotateSecret` without the `RotationRules` parameter.

> If you do not include the configuration parameters, the operation starts a rotation with the values already stored in the secret. After the rotation completes, the protected service and its clients all use the new version of the secret.

https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RotateSecret.html

This should be executed before any other components have started since they will be requesting this token on startup and then cache it.
